.TH filer.out 1 "20/07/2023" "Version 1.0" "Simple File System Manager"
.SH NAME
filer.out - Manage a Simple File System
.SH SYNOPSIS
The program doesn't use any command line configuration.
.SH DESCRIPTION
This program gives a prompt which allows for simple command line management of a file containing Simple File System data.
.SH File System
.PP
The Simple File System uses five main structures. These structures are the following: 
.B directory_listing_entry initial_directory_listing directory_listing initial_file_descriptor file_descriptor
. Each entry is packed and in the following description each field goes from lowest 

.PP
.B directory_listing_entry
is a 16 byte structure within the
.B initial_directory_listing
structure and
.B directory_listing
structures.

.PP
The four other structures are all 1024 bytes in size. For file descriptor structures, the first 1000 bytes are used for file data with 24 bytes at the end for more metadata.
In directory listing structures contain also 1000 bytes, of which 992 bytes are used. This accounts for 62 directory_listing_entry structures.

.PP
Format of
.B directory_listing_entry
structuers:
.PP
	File Name - 13 byte field containing the name and extension of the file in ASCII characters.
.PP
	Sector - 2 byte field containing the sector of the file's intial descriptor.
.PP
	Attributes - 1 byte field containing various bits to indicate different attributes.

.PP
The bit field of the attributes field looks as such:
.PP
	D E U 0 0 0 0 0
.PP
	D(eleted) - 1: the file has been deleted
.PP
	E(xists) - 1: A file exists at this location (deleted or not)
.PP
	U(sable) - 1: File contains usable blocks, could be valuable to search

.PP

.PP
Fromat of the
.B initial_directory_listing



.SH BUGS
Fragmentation in the file system - Bitmap would be able to fix this.

.SH AUTHOR
awewsomegamer (awewsomegamer@gmail.com)
.SH SEE ALSO